### PR TITLE
get-secretkey: simple python tool to fetch the authentication keys

### PR DESCRIPTION
**Pull request by osresearch**
This tool will login to the Fossil/Skagen servers and fetch the secret keys for all watches associated with the account.

### CODE REVIEW

**Comment by dakhnod** [comment]
this seems to be limited to the skagen API to me.
The fossil API ditched the secret-key endpoint I believe, so that is sadly not an option.

Also, the Fossil API does seem to require HMAC auth as of recently, which complicates the request quite a bit.

**Comment by arjan-s** [comment]
Actually, this script works perfectly for Fossil too, if you modify the `base_url` line to:
```
base_url = 'https://c.fossil.com/v2.1'
```
So I would suggest @osresearch to extend this script with another argument to allow the user to select between the Fossil and Skagen base URLs.

**Comment by dakhnod** [comment]
@arjan-s are you sure it works for gen.6?

**Comment by arjan-s** [comment]
No, I don't have a gen6. But it works for my gen1 Collider.
The official app does all v3 API stuff with HMAC for my watch too, but this v2.1 API still works.

**Comment by dakhnod** [comment]
It works for gen. 6.
I am hesitant about this since the watch needs to be registered with the fossil account in order for this to work, which is slightly against my intent...

**Comment by dakhnod** [comment]
sorry, I am a bit hesitant to include URLs referencing skagen or fossil...

**Pull request closed without merging**
